// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComputerName():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadManagerCategoriesJSON():Promise<string>;

export function LoadManagerGamesJSON():Promise<string>;

export function LoadManagerQuickAccessJSON():Promise<string>;

export function LoadManagerSettingsJSON():Promise<string>;

export function LoadManagerTagsJSON():Promise<string>;

export function ReadManagerImageDataURL(arg1:string):Promise<string>;
