// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientIdentityJSON():Promise<string>;

export function GetComputerName():Promise<string>;

export function GetWindowsStartupStatus():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;

export function LoadManagerCategoriesJSON():Promise<string>;

export function LoadManagerClientsJSON():Promise<string>;

export function LoadManagerGamesJSON():Promise<string>;

export function LoadManagerLinksJSON():Promise<string>;

export function LoadManagerQuickAccessJSON():Promise<string>;

export function LoadManagerSettingsJSON():Promise<string>;

export function LoadManagerTagsJSON():Promise<string>;

export function ReadManagerImageDataURL(arg1:string):Promise<string>;

export function ShowNativeMessage(arg1:string,arg2:string):Promise<void>;

export function ShowNativeMessageWithIcon(arg1:string,arg2:string,arg3:string):Promise<void>;
