// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComputerName() {
  return window['go']['main']['App']['GetComputerName']();
}

export function GetWindowsStartupStatus() {
  return window['go']['main']['App']['GetWindowsStartupStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function LoadManagerCategoriesJSON() {
  return window['go']['main']['App']['LoadManagerCategoriesJSON']();
}

export function LoadManagerGamesJSON() {
  return window['go']['main']['App']['LoadManagerGamesJSON']();
}

export function LoadManagerQuickAccessJSON() {
  return window['go']['main']['App']['LoadManagerQuickAccessJSON']();
}

export function LoadManagerSettingsJSON() {
  return window['go']['main']['App']['LoadManagerSettingsJSON']();
}

export function LoadManagerTagsJSON() {
  return window['go']['main']['App']['LoadManagerTagsJSON']();
}

export function ReadManagerImageDataURL(arg1) {
  return window['go']['main']['App']['ReadManagerImageDataURL'](arg1);
}

export function ShowNativeMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowNativeMessage'](arg1, arg2);
}

export function ShowNativeMessageWithIcon(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowNativeMessageWithIcon'](arg1, arg2, arg3);
}
