// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractExecutableIcon(arg1) {
  return window['go']['main']['App']['ExtractExecutableIcon'](arg1);
}

export function GetCoverDataURL(arg1) {
  return window['go']['main']['App']['GetCoverDataURL'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetWindowsStartupStatus() {
  return window['go']['main']['App']['GetWindowsStartupStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IGDBCredentialsConfigured() {
  return window['go']['main']['App']['IGDBCredentialsConfigured']();
}

export function IGDBEnvHintPath() {
  return window['go']['main']['App']['IGDBEnvHintPath']();
}

export function IGDBFetchGameArt(arg1) {
  return window['go']['main']['App']['IGDBFetchGameArt'](arg1);
}

export function IGDBSearchGames(arg1) {
  return window['go']['main']['App']['IGDBSearchGames'](arg1);
}

export function ImportCategoryIcon(arg1) {
  return window['go']['main']['App']['ImportCategoryIcon'](arg1);
}

export function ImportCoverImage(arg1, arg2) {
  return window['go']['main']['App']['ImportCoverImage'](arg1, arg2);
}

export function ImportGameIcon(arg1) {
  return window['go']['main']['App']['ImportGameIcon'](arg1);
}

export function ImportLinkIcon(arg1, arg2) {
  return window['go']['main']['App']['ImportLinkIcon'](arg1, arg2);
}

export function ImportPopularImage(arg1, arg2) {
  return window['go']['main']['App']['ImportPopularImage'](arg1, arg2);
}

export function ImportSettingsImage(arg1, arg2) {
  return window['go']['main']['App']['ImportSettingsImage'](arg1, arg2);
}

export function LoadCategoriesJSON() {
  return window['go']['main']['App']['LoadCategoriesJSON']();
}

export function LoadClientsJSON() {
  return window['go']['main']['App']['LoadClientsJSON']();
}

export function LoadGamesJSON() {
  return window['go']['main']['App']['LoadGamesJSON']();
}

export function LoadLinksJSON() {
  return window['go']['main']['App']['LoadLinksJSON']();
}

export function LoadQuickAccessJSON() {
  return window['go']['main']['App']['LoadQuickAccessJSON']();
}

export function LoadSettingsJSON() {
  return window['go']['main']['App']['LoadSettingsJSON']();
}

export function LoadTagsJSON() {
  return window['go']['main']['App']['LoadTagsJSON']();
}

export function PickExecutableFile() {
  return window['go']['main']['App']['PickExecutableFile']();
}

export function PickImageFile() {
  return window['go']['main']['App']['PickImageFile']();
}

export function PickPopularJsonFile() {
  return window['go']['main']['App']['PickPopularJsonFile']();
}

export function PickScriptFile() {
  return window['go']['main']['App']['PickScriptFile']();
}

export function ReadImageFileDataURL(arg1) {
  return window['go']['main']['App']['ReadImageFileDataURL'](arg1);
}

export function SaveCategoriesJSON(arg1) {
  return window['go']['main']['App']['SaveCategoriesJSON'](arg1);
}

export function SaveClientsJSON(arg1) {
  return window['go']['main']['App']['SaveClientsJSON'](arg1);
}

export function SaveGamesJSON(arg1) {
  return window['go']['main']['App']['SaveGamesJSON'](arg1);
}

export function SaveLinksJSON(arg1) {
  return window['go']['main']['App']['SaveLinksJSON'](arg1);
}

export function SaveQuickAccessJSON(arg1) {
  return window['go']['main']['App']['SaveQuickAccessJSON'](arg1);
}

export function SaveSettingsJSON(arg1) {
  return window['go']['main']['App']['SaveSettingsJSON'](arg1);
}

export function SaveTagsJSON(arg1) {
  return window['go']['main']['App']['SaveTagsJSON'](arg1);
}

export function SetLaunchOnWindowsStartup(arg1) {
  return window['go']['main']['App']['SetLaunchOnWindowsStartup'](arg1);
}
