// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractExecutableIcon(arg1:string):Promise<string>;

export function GetCoverDataURL(arg1:string):Promise<string>;

export function GetDataDir():Promise<string>;

export function GetWindowsStartupStatus():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportCategoryIcon(arg1:string):Promise<string>;

export function ImportCoverImage(arg1:string,arg2:number):Promise<string>;

export function ImportGameIcon(arg1:string):Promise<string>;

export function ImportLinkIcon(arg1:string,arg2:number):Promise<string>;

export function ImportSettingsImage(arg1:string,arg2:string):Promise<string>;

export function LoadCategoriesJSON():Promise<string>;

export function LoadClientsJSON():Promise<string>;

export function LoadGamesJSON():Promise<string>;

export function LoadLinksJSON():Promise<string>;

export function LoadQuickAccessJSON():Promise<string>;

export function LoadSettingsJSON():Promise<string>;

export function LoadTagsJSON():Promise<string>;

export function PickExecutableFile():Promise<string>;

export function PickImageFile():Promise<string>;

export function ReadImageFileDataURL(arg1:string):Promise<string>;

export function SaveCategoriesJSON(arg1:string):Promise<void>;

export function SaveClientsJSON(arg1:string):Promise<void>;

export function SaveGamesJSON(arg1:string):Promise<void>;

export function SaveLinksJSON(arg1:string):Promise<void>;

export function SaveQuickAccessJSON(arg1:string):Promise<void>;

export function SaveSettingsJSON(arg1:string):Promise<void>;

export function SaveTagsJSON(arg1:string):Promise<void>;

export function SetLaunchOnWindowsStartup(arg1:boolean):Promise<void>;
